// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5yljXNtV__uVW173JChxW7oqR6ZkUGE',
    appId: '1:66192424676:web:6d47f8fb8324d025c0b6f1',
    messagingSenderId: '66192424676',
    projectId: 'periody-a3a06',
    authDomain: 'periody-a3a06.firebaseapp.com',
    storageBucket: 'periody-a3a06.firebasestorage.app',
    measurementId: 'G-L2XSW0700F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADcOC0LxYiBOyzIQxZtFqUWf-PZ19dWCk',
    appId: '1:66192424676:android:1be277de3aae2199c0b6f1',
    messagingSenderId: '66192424676',
    projectId: 'periody-a3a06',
    storageBucket: 'periody-a3a06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1oJ4K15V-jYjNY_nO5hWMZ0nFPhtXNI',
    appId: '1:66192424676:ios:ff182b544c344b01c0b6f1',
    messagingSenderId: '66192424676',
    projectId: 'periody-a3a06',
    storageBucket: 'periody-a3a06.firebasestorage.app',
    iosBundleId: 'com.example.periody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1oJ4K15V-jYjNY_nO5hWMZ0nFPhtXNI',
    appId: '1:66192424676:ios:ff182b544c344b01c0b6f1',
    messagingSenderId: '66192424676',
    projectId: 'periody-a3a06',
    storageBucket: 'periody-a3a06.firebasestorage.app',
    iosBundleId: 'com.example.periody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx5yljXNtV__uVW173JChxW7oqR6ZkUGE',
    appId: '1:66192424676:web:f5182420afb815a3c0b6f1',
    messagingSenderId: '66192424676',
    projectId: 'periody-a3a06',
    authDomain: 'periody-a3a06.firebaseapp.com',
    storageBucket: 'periody-a3a06.firebasestorage.app',
    measurementId: 'G-PC9Q1QE6SY',
  );
}
